---
purpose: development
cloudformation_retries: 0

agnosticv_meta:
  idle_after_deploy: 26
  idle_after_start: 12

__meta__:
  deployer:
    scm_ref: development
    scm_url: 'https://github.com/vincepower/agnosticd.git'
    scm_type: git
    type: agnosticd
